name: Docker in Docker

on:
  push:
    branches:
    - did/*

jobs:
  build-docker-compose:
    name: test DinD
    runs-on: ubuntu-latest

    steps:
    - name: docker version
      uses: docker://docker/compose:1.25.0-rc2
      with:
        args: docker version

    - name: checkout
      uses: actions/checkout@v1 # --quiet
      with:
        fetch-depth: 1

    - name: docker-compose config
      env:
        LLB: docker-build
        INVOCATION_ID: dunnowhattoputhere
      uses: docker://docker/compose:1.25.0-rc2
      with:
        args: docker-compose -f docker-compose.yml -f docker-compose.stage-2.yml config

    - name: Building images
      env:
        LLB: docker-build
        INVOCATION_ID: dunnowhattoputhere
      uses: docker://docker/compose:1.25.0-rc2
      with:
        args: docker-compose build
        # args: docker-compose build --parallel

    - name: Building images that depend on the previous stage
      env:
        LLB: docker-build
        INVOCATION_ID: dunnowhattoputhere
      uses: docker://docker/compose:1.25.0-rc2
      with:
        args: docker-compose -f docker-compose.stage-2.yml build --parallel

    - name: Show tagged images
      run: docker images
