name: build Docker images

on:
  push:
    branches:
    - build/*
  pull_request:
  - opened

jobs:
  build-docker-compose:
    name: build with docker-compose
    runs-on: ubuntu-latest

    steps:
    - name: checkout
      uses: actions/checkout@v1

    - name: docker-compose build
      run: |
        docker-compose config
        docker-compose build
        docker images

  build-buildx:
    name: build with buildx bake
    runs-on: ubuntu-latest

    steps:
    - name: buildx dependencies
      env:
        BUILDX_VER: v0.3.0
        DOCKER_CLI_EXPERIMENTAL: enabled
        DOCKER_BUILDKIT: 1
        PREFER_BUILDCTL: 1
      run: |
        docker version
        docker info
        mkdir -p ~/.docker/cli-plugins/
        export PATH=~/.docker/cli-plugins/:$PATH
        curl --silent -L https://github.com/docker/buildx/releases/download/"$BUILDX_VER"/buildx-"$BUILDX_VER".linux-amd64 > ~/.docker/cli-plugins/docker-buildx
        chmod a+x ~/.docker/cli-plugins/docker-buildx
        docker-buildx version
        # docker-buildx create --use --buildkitd-flags '--oci-worker-gc=false'

    - name: checkout
      uses: actions/checkout@v1

    - name: buildx bake
      env:
        DOCKER_CLI_EXPERIMENTAL: enabled
        PREFER_BUILDCTL: 1
        DOCKER_BUILDKIT: 1
      run: |
        export PATH=~/.docker/cli-plugins/:$PATH
        docker-compose -f docker-compose.yml -f buildx.yml config
        docker-buildx bake -f docker-compose.yml -f buildx.yml --print
        # docker-buildx bake --progress plain -f docker-compose.yml -f buildx.yml
        docker-buildx bake -f docker-compose.yml -f buildx.yml
        docker images
